set nocompatible              " be iMproved, required

syntax enable                   " enable syntax highlighting
set relativenumber              " show line numbers. use 'number' for normal
                                " line numbering, 'relativenumber' for relative
set ts=4                        " set tabs to have 4 spaces
set autoindent                  " indent when moving to the next line while
                                " writing code
set expandtab                   " expand tabs into spaces
set shiftwidth=4                " when using the >> or << commands,
                                " shift lines by 4 spaces
set tabstop=4                   " set number of spaces for a tab
set softtabstop=4
set showmatch                   " show matching part of the pair for [], (), {}
set nowrap                      " set so long lines don't wrap around
set colorcolumn=80              " column guideline
set cursorline                  " highlight current line
set synmaxcol=2500              " limit syntax highlighting
                                " on lines that are too long
set numberwidth=5               " increase minimal length for line numbers
" set nojoinspaces              " on join, only insert spaces after '.', '?', '!'
let python_highlight_all = 1    " enable all Python syntax highlighting features
set t_Co=256                    " set number of colors to 256. must be
                                " set before colorscheme
set wildmenu                    " auto-complete for commands
set wildmode=longest,full       " customize how auto-complete for
                                " commands will work
set visualbell                  " set visual flashing on error
set noerrorbells                " disable PC beep on error
set showcmd                     " show entered command or number of selected chars/lines at the bottom



filetype off                  " disable file type detection (required by vundle)

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/plugins/Vundle.vim

"call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
call vundle#begin('~/.vim/plugins')

    " let Vundle manage Vundle, required
    Plugin 'VundleVim/Vundle.vim'

    Plugin 'altercation/vim-colors-solarized'
    Plugin 'bling/vim-airline'
    Plugin 'vim-airline/vim-airline-themes'
    Plugin 'tomtom/tcomment_vim'
    Plugin 'tpope/vim-fugitive'

    " plugin that can generate an airline-like tmux statusline
    "Plugin 'edkolev/tmuxline.vim'

    " All of your Plugins must be added before the following line
call vundle#end()            " required

filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on

" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line


" set vim theme
set background=dark

" let g:solarized_termtrans = 1
let g:solarized_termcolors = 256
let g:solarized_contrast = 'high'
let g:solarized_visibility = 'high'

colorscheme solarized

" enable powerline fonts for airline
let g:airline_powerline_fonts = 1

" set theme for airline
let g:airline_theme = 'base16'
" set airline to always be on
set laststatus=2


highlight ColorColumn ctermbg=235
" highlight CursorLine ctermbg=235

" ----------------------------------------------------------------------
" | Mappings                                                   |
" ----------------------------------------------------------------------
" change the leader if needed
" let mapleader = ','

" save and run file
nmap <leader>s <Esc>:w<CR>:!%:p<CR>

" toggle commenting using TComment
nmap <leader>c :TComment<CR>

nmap <leader>gd :Gvdiff<CR>

" clear on exit
" au VimLeave * :!clear

