set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/plugins/Vundle.vim

"call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
call vundle#begin('~/.vim/plugins')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

Plugin 'altercation/vim-colors-solarized'
Plugin 'bling/vim-airline'

" plugin that can generate an airline-like tmux statusline
"Plugin 'edkolev/tmuxline.vim'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

" enable syntax highlighting
syntax enable

" show line numbers
set number

" set tabs to have 4 spaces
set ts=4

" indent when moving to the next line while writing code
set autoindent

" expand tabs into spaces
set expandtab

" when using the >> or << commands, shift lines by 4 spaces
set shiftwidth=4

" set number of spaces for a tab
set tabstop=4

set softtabstop=4

" show a visual line under the cursor's current line
" set cursorline

" show the matching part of the pair for [], (), {}
set showmatch

" set so long lines don't wrap around
set nowrap

" enable all Python syntax highlighting features
let python_highlight_all = 1

" set number of colors to 256. must be set before colorscheme
set t_Co=256

" set vim theme
set background=dark

" let g:solarized_termtrans = 1
" let g:solarized_termcolors = 256
let g:solarized_contrast = 'high'
let g:solarized_visibility = 'high'

colorscheme solarized

" enable powerline fonts for airline
let g:airline_powerline_fonts = 1

" set theme for airline
let g:airline_theme = 'base16'
" set airline to always be on
set laststatus=2

" ----------------------------------------------------------------------
" | Mappings                                                   |
" ----------------------------------------------------------------------

" save and run file
map <F5> <Esc>:w<CR>:!%:p<CR>


" clear on exit
" au VimLeave * :!clear
