#!/usr/bin/zsh

# useful commands: ############################
# rg - ripgrep - alternative to grep
# pgcli - alternative to psql
# tig - git viewer and manager
# autojump.rs - cd with learning feature. install standard autojump before
#     for extra functionality not covered by the rust port
# #############################################

dotfiles_dir=$HOME'/dotfiles'
zsh_dir=$dotfiles_dir'/shell/zsh'
gen_shell_dir=$dotfiles_dir'/shell/generic'
git_dir=$dotfiles_dir'/git'

# functions ###################################
sal() {
  rg --color=always --heading --no-ignore \
    $gen_shell_dir/aliases \
    $git_dir/gitconfig \
    -SLne "$*" | pypager
}

j() {
  cd $(find ${1:-.} -type d | fzf)
}
# #############################################


# #### aliases:

# ### generic aliases:
# alias history="history 0"
alias _="sudo"

# ### apt aliases:
apt_cmd='apt-get '
cache_cmd='apt-cache '
s_apt_cmd='_ '$apt_cmd

alias apti=$s_apt_cmd'install'
alias aptr=$s_apt_cmd'remove'
alias aptp=$s_apt_cmd'purge'  # completely removes packages

alias aptc=$s_apt_cmd'clean'
alias aptchk=$s_apt_cmd'check'

alias aptu=$s_apt_cmd'update'
alias aptU=$s_apt_cmd'upgrade'
alias aptuU='aptu && aptU'

alias apts=$cache_cmd'search'
alias aptsn='apts --names-only'
alias aptl=$cache_cmd'pkgnames'  # lists packages. can also search with it.

alias aptinfo=$cache_cmd'show'  # show info for package
alias aptdep=$cache_cmd'showpkg' # check dependecies
alias aptstat=$cache_cmd'stats'

# ### git aliases
alias gg='git gui &'

# ### ls aliases
alias la='ls -la'
alias ll='ls -a'

# ### ssh aliases
ssh_agent='eval `ssh-agent -s`'
ssh_add_all='ssh-add $HOME/.ssh/^(*.pub|known_hosts|config|authorized_keys)'
alias ssha=$ssh_agent
alias sshl='ssh-add -l'
alias sshad=$ssh_add_all
alias sshaa=$ssh_agent' && '$ssh_add_all

# ### pip aliases
pip_cmd='pip '
alias pipa=$pip_cmd'install'
alias pipd=$pip_cmd'uninstall'
alias pipf=$pip_cmd'freeze'
alias pipl=$pip_cmd'list'

# ### tmux aliases
alias txm='tmux'
alias txl='tmux ls'
alias txn='tmux new -s'
alias txa='tmux attach -t'

# ### docker aliases
dk_cmd='docker'
dkc_cmd='docker-compose'
alias dk="$dk_cmd"
alias dkb="$dk_cmd build"

alias dk-ci="$dk_cmd container inspect"  # todo: create function that pipes in less
alias dk-cls="$dk_cmd container ls -a"

# todo: convert this to a python function
# equivalent, but check: `sudo docker rmi $(sudo docker images -f "dangling=true" -q)``
alias dk-idang="$dk_cmd images -f \"dangling=true\""

_docker_clear_images() {
  $dk_cmd rmi $(dk-idang -q)
}

alias dk-iclr=$_docker_clear_images
alias dk-ils="$dk_cmd images ls -a"

alias dk-l="$dk_cmd logs -tf --tail"

alias dkc=$dkc_cmd
alias dkc-upd="$dkc_cmd up -d"


# ### other aliases
alias e='nvim'
alias vim='nvim'
alias clear='echo -en "\ec"'
alias clr='clear'
alias c='clear'
alias g='git'
alias :q='exit'
alias q='exit'
alias ytp='$HOME/dotfiles/players/mpsyt/start.zsh'
alias dsz='du -h --max-depth=1 . | sort -rh'


alias zreload='source ~/.zshrc'
# alias to shift a workspace in i3
alias shiftws='i3-msg move workspace to output'

# python related
alias runp=$HOME/dotfiles/utils/run_in_env.sh
# todo: remove this
# alias pym='source $MAIN_VENV/activate && source $MAIN_VENV/virtualenvwrapper.sh'
# alias python=python3
# alias virtualenv='python -m virtualenv'
alias pip='python -m pip'
