if [ -f $HOME/.bashrc.xbkp ]; then
    . $HOME/.bashrc.xbkp
fi

# set terminal to xterm with 256 colors
# if [ -e /usr/share/terminfo/x/xterm-256color ]; then
#     export TERM='xterm-256color'
# else
#     export TERM='xterm-color'
# fi

