if [ -f $HOME/.bashrc.alt ]; then
    . $HOME/.bashrc.alt
fi

# set terminal to xterm with 256 colors
if [ -e /usr/share/terminfo/x/xterm-256color ]; then
    export TERM='xterm-256color'
else
    export TERM='xterm-color'
fi

