 #!/usr/bin/env zsh

# Set up the prompt

# autoload -Uz promptinit
# promptinit
# prompt adam1

setopt histignorealldups sharehistory

# Use emacs keybindings even if our EDITOR is set to vi
bindkey -e

# Keep 2000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=2000
SAVEHIST=2000
HISTFILE=~/.zsh_history

# Use modern completion system
autoload -Uz compinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
eval "$(dircolors -b)"
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'


# load global env
source $HOME/dotfiles/shell/zsh/global_env.zsh


if ! [ -d $DOTFILES_DIR ]; then
  # can only happen if using a different directory
  echo "WARN: Dotfiles dir could not be found."
  return -1
fi


# load custom functions
source $ZSH_CONFIG_DIR/functions.zsh


# load local env if it exists
if [ -f $HOME/local_env.zsh ]; then
  source $HOME/local_env.zsh  # TODO: create a function to source_if_exist_with_opt_warn
fi

if ! check_command git FATAL ; then
  return -1
fi

if check_command figlet INFO ; then
  show_banner
fi

# check usual apps
check_command rg
check_command autojump
check_command fzf
check_command docker INFO 0
check_command nvim
check_command make
check_command tig
check_command pypager
check_command pgcli


if ! [ -d $SPACEVIM_CHECK_DIR ]; then
  echo "WARN: SpaceVim is not installed. Install using 'install_spacevim' and run 'SPUpdate' if needed."
fi


# load aliases
source $DOTFILES_DIR/shell/generic/aliases


# install zplug
if ! [ -d $ZPLUG_HOME ]; then
  git clone https://github.com/zplug/zplug $ZPLUG_HOME
fi

# load zplug config
source $ZSH_CONFIG_DIR/zplugrc

# options:
setopt histignorespace  # history ignores commands that start with space

# enable autojump. TODO: perhaps not needed?
# TODO: create install command for autojump + autojump.rs
# source /usr/share/autojump/autojump.sh

# sys envs
export PATH="$HOME/.cargo/bin:$PATH"
# required for autojump to work properly
# export PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND ;} history -a"


# start the system python env if defined
startp

# install completion for bash
autoload -U +X bashcompinit && bashcompinit

# install completion for consul
complete -o nospace -C /usr/bin/consul consul

